/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author Yamlikho Karma
 */
public class formProses extends javax.swing.JFrame {

    /**
     * Creates new form formProses
     */
    static int[][] bestJadwal;
    static double cr;
    static double mr;
    static int popsize;
    static int iterasi;
    static String inputFile;
    Scanner baca = new Scanner(System.in);

    public formProses() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        psField = new javax.swing.JTextField();
        iterasiField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        crField = new javax.swing.JTextField();
        mrField = new javax.swing.JTextField();
        fileButton = new javax.swing.JToggleButton();
        mulaiButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("PopSize");

        jLabel3.setText("Jumlah Generasi");

        psField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psFieldActionPerformed(evt);
            }
        });

        iterasiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterasiFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Crossover Rate (Cr)");

        jLabel5.setText("Mutation Rate (Cr)");

        fileButton.setText("Import Data");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        mulaiButton.setText("Generate");
        mulaiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mulaiButtonMouseClicked(evt);
            }
        });
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("PARAMETER INPUT");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jLabel10.setText("Iterasi :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(psField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iterasiField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mrField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(mulaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(crField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(psField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fileButton)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(iterasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(mrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mulaiButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proses Generate Jadwal", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("JADWAL MATA PELAJARAN");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable);

        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hasil Jadwal", jPanel2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("PENJADWALAN MATA PELAJARAN");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("YAYASAN BANI SYIHAB NARULLOH MALANG");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText(" PONDOK PESANTREN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //private void proses(int ps, double cr, double mr) throws SQLException, IOException, BiffException{
    //    penjadwalan jadwal = new penjadwalan("kacuk.xls", ps, cr, mr);        
    //}
    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        popsize = Integer.parseInt(psField.getText());
        cr = Double.parseDouble(crField.getText());
        iterasi = Integer.parseInt(iterasiField.getText());
        mr = Double.parseDouble(mrField.getText());

        DefaultTableModel tablemodel;

        try {
            penjadwalan jadwal = new penjadwalan(inputFile, popsize, cr, mr);
            //jadwal.run(iterasi);

            /*jTextArea1.append("Popsize: " + popsize + "\n"
                +"Generasi: " + iterasi + "\n"
                +"Cr: " + cr + "\n"
                +"Mr: " + mr + "\n\n"
                +"Kromosom Terbaik: "  + "\n"
                +"Fitnes Maks: " + penjadwalan.getFitnesMax() + "\n");
            */

            //Proses Inisialisasi
            int kro[][] = jadwal.inisialisasi();
            int populasiGabungan[][] = new int[popsize + jadwal.getOffspringCrossover() + jadwal.getOffspringMutasi()][jadwal.getPjgKromosom()];

            for (int i = 0; i < iterasi; i++) {
                jTextArea1.append("Iterasi ke " + (i + 1) + "\n");

                //Proses Reproduksi
                int[][] childCrossover = jadwal.crossover(kro);
                int[][] childMutasi = jadwal.mutasi(kro);
                populasiGabungan = jadwal.evaluasi(kro, childCrossover, childMutasi);
                double[] fit = jadwal.getFitness();

                //Proses Seleksi
                int[][] best = jadwal.seleksi(populasiGabungan);

                //Menampilkan Kro Terbaik tiap Iterasi
                //for (int j = 0; j < best.length; j++) {
                    //    jTextArea1.append(Arrays.toString(best[j]) + "\n");
                    //System.out.println(Arrays.toString(best[j]));
                    //}

                //Menampilkan Max Fitness
                jTextArea1.append("Fitness Max: " + String.valueOf(jadwal.getFitnesMax()));
                jTextArea1.append("\n \n");
                kro = best;

            }

            int[] bestKro = kro[0];
            //jTextArea1.append(String.valueOf(bestKro.length));
            int[][]jdw = jadwal.bentuk_jadwal(bestKro);
            formProses.bestJadwal = jdw;

            Object[] row = {"PAGI", "MALAM", "PAGI", "MALAM", "PAGI", "MALAM", "PAGI", "MALAM", "PAGI", "MALAM"};
            tablemodel = new DefaultTableModel(row, 0);
            jTable.setModel(tablemodel);
            //for(int b=0; b<1; b++){
                for (int b = 0; b < jadwal.id_kelas.length; b++) {
                    tablemodel.addRow(new Object[]{
                        String.valueOf(jdw[b][0]), String.valueOf(jdw[b][1]), String.valueOf(jdw[b][2]),
                        String.valueOf(jdw[b][3]), String.valueOf(jdw[b][4]), String.valueOf(jdw[b][5]),
                        String.valueOf(jdw[b][6]), String.valueOf(jdw[b][7]), String.valueOf(jdw[b][8]),
                        String.valueOf(jdw[b][9])});
            }
            //}
        } catch (SQLException ex) {
            Logger.getLogger(formProses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formProses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(formProses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void mulaiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mulaiButtonMouseClicked
        //jTextArea1.setText("a");
    }//GEN-LAST:event_mulaiButtonMouseClicked

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        FileFilter filter = new FileNameExtensionFilter("Excel 97-2003 Workbook (.xls)", "xls");
        JFileChooser n = new JFileChooser();
        n.setFileFilter(filter);
        n.showOpenDialog(this);
        if (n.getSelectedFile() == null) {
            return;
        }
        File file = n.getSelectedFile();
        inputFile = file.getAbsolutePath();
    }//GEN-LAST:event_fileButtonActionPerformed

    private void iterasiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iterasiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iterasiFieldActionPerformed

    private void psFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        WritableWorkbook workbook;
        File excelFile = new File(inputFile);
        Workbook workbookRead;
        String guru[], materi[], kelas[], lokasi[];
        
        try {
            workbookRead = Workbook.getWorkbook(excelFile);
            Sheet sheetRead = workbookRead.getSheets()[0];
            
            guru = new String[sheetRead.getRows()];
            materi = new String[sheetRead.getRows()];
            kelas = new String[sheetRead.getRows()];
            lokasi = new String[sheetRead.getRows()];
            
            for (int i = 0; i < sheetRead.getRows(); i++) {
                guru[i] = sheetRead.getCell(2, i).getContents();
                materi[i] = sheetRead.getCell(3, i).getContents();
                kelas[i] = sheetRead.getCell(4, i).getContents();
                lokasi[i] = sheetRead.getCell(5, i).getContents();
            }
            
            workbook = Workbook.createWorkbook(new File("/home/xechrome/hasil.xls"));
            WritableSheet sheet = workbook.createSheet("Tony", 0);
            int[][] jdw = formProses.bestJadwal;
            String[] hari = {"Senin", "Selasa", "Rabu", "Kamis", "Jumat"};
            String[] waktu = {"Pagi", "Malam"};
            String[] category = {"Guru", "Kelas", "Materi", "Lokasi"};
            int hariCount = 0;
            int col = 0;
            int colSched = 0;
            while(hariCount < hari.length){
                Label l = new Label(col, 0, hari[hariCount]);
                sheet.addCell(l);
                int waktuCount = 0;
                while(waktuCount < waktu.length){
                    Label lWaktu = new Label(col, 1, waktu[waktuCount]);
                    sheet.addCell(lWaktu);
                    int categoryCount = 0;
                    while(categoryCount < category.length){
                        Label lKategori = new Label(col, 2, category[categoryCount]);
                        sheet.addCell(lKategori);
                        for (int j = 0; j < jdw.length; j++) {
                            int index = jdw[j][colSched];
                            String content;
                            switch (col%4) {
                                case 0:
                                    content = guru[index-1];
                                    break;
                                case 1:
                                    content = kelas[index-1];
                                    break;
                                case 2:
                                    content = materi[index-1];
                                    break;
                                default:
                                    content = lokasi[index-1];
                                    break;
                            }
                            Label lKode = new Label(col, j+3, content);
                            sheet.addCell(lKode);
                        }
                        col++;
                        categoryCount++;
                    }
                    colSched++;
                    waktuCount++;
                }
                hariCount++;
            }
            
//            for (int i = 0; i < 10; i++) {
//                
//                if(i%2 == 0){
//                    Label l = new Label(i, 0, hari[i/2]);
//                    sheet.addCell(l);
//                    waktu = "Pagi";
//                } else {
//                    waktu = "Malam";
//                }
//                
//                Label lhari = new Label(i, 1, waktu);
//                sheet.addCell(lhari);
//                
                
//            }
                
            workbook.write();
            workbook.close();
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formProses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProses().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField crField;
    private javax.swing.JToggleButton fileButton;
    private javax.swing.JTextField iterasiField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mrField;
    private javax.swing.JToggleButton mulaiButton;
    private javax.swing.JTextField psField;
    // End of variables declaration//GEN-END:variables
}
